create table if not exists public.contact_submissions (
    id bigint generated by default as identity primary key,
    name text not null,
    email text not null,
    service text,
    message text not null,
    created_at timestamptz not null default now()
);
alter table public.contact_submissions enable row level security;
revoke all on table public.contact_submissions
from anon,
    authenticated;
grant insert on table public.contact_submissions to service_role;